draw_sprite_ext(
	sprite_index,
	image_index,
	floor(x+extraX),
	floor(y+extraY),
	image_xscale,
	image_yscale,
	image_angle,
	image_blend,
	image_alpha
);
//draw_text(10,10,DISTANCE);
//draw_text(10,30,image_index);